--
-- PostgreSQL database dump
--

\restrict nXH9y54vwd9ZFZVWpH4O702voQYTqBUxtikUpY4uhM9I6hBY3dp5LonJ8gSTdfu

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_details (
    id bigint NOT NULL,
    description character varying(4000),
    dimensions character varying(255),
    manufactured_country character varying(255),
    warranty character varying(255),
    weight double precision
);


--
-- Name: product_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    brand character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    discount_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    stock integer NOT NULL,
    detail_id bigint NOT NULL
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    comment character varying(2000),
    rating integer NOT NULL,
    review_date date NOT NULL,
    reviewer character varying(255) NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product_details; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_details (id, description, dimensions, manufactured_country, warranty, weight) FROM stdin;
2	สมาร์ตโฟนจอ 6.1 นิ้ว กล้อง 48 MP ความจุ 256 GB	15x7x0.8 cm	China	2 Years	0.19
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, brand, category, discount_type, name, price, stock, detail_id) FROM stdin;
2	Apple	Electronics	SEASONAL	iPhone 15 Pro (673380062-2 SEC 1)	39000	8	2
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reviews (id, comment, rating, review_date, reviewer, product_id) FROM stdin;
3	ใช้งานดี กล้องคมชัด	5	2026-09-08	Student 673380062-2	2
4	จัดส่งไว แพ็กสินค้าดี	4	2026-09-08	Reviewer 2	2
\.


--
-- Name: product_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_details_id_seq', 2, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 2, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reviews_id_seq', 4, true);


--
-- Name: product_details product_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_details_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: products ukfq6xkbp2dny2wua6wcuh5jcwj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukfq6xkbp2dny2wua6wcuh5jcwj UNIQUE (detail_id);


--
-- Name: products fka9j512fdisl3ol4ix883w8bcj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fka9j512fdisl3ol4ix883w8bcj FOREIGN KEY (detail_id) REFERENCES public.product_details(id);


--
-- Name: reviews fkpl51cejpw4gy5swfar8br9ngi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- PostgreSQL database dump complete
--

\unrestrict nXH9y54vwd9ZFZVWpH4O702voQYTqBUxtikUpY4uhM9I6hBY3dp5LonJ8gSTdfu

